version: "3.7"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
      - 9229:9229

  postgres:
    image: postgres:11
    ports:
        - 5432:5432
    volumes:
        - .pgdata/db:/var/lib/postgresql
        - .pgdata/db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
